### ISSUE TITLE
Suggestion : offering the thumbnail link

### ISSUE THREAD

**Issue by FrancoisH** [Dymantic/laravel-instagram-feed#11]
Hello there,

I'm trying to override the parseMedia method... or simply return the default object from Instagram rather than your parsed feed...

I need to get the thumbnail for the video, not the video itself.

Could you add an option to allow this?

Thanks.

**Comment by michaeljoyner** [comment]
Hi @FrancoisH, I'd be happy to look into that. I'm currently on holiday at the moment, so it would only be at the end of the weekend or early next week. Feel free to send a PR of you need it before then.

**Comment by FrancoisH** [comment]
Ideally it would be nice to be able to get another user feed using the id connected too... I'll have to look into your library to do so.

**Comment by michaeljoyner** [comment]
I'm closing this seeing as nothing is happening here.
