### ISSUE TITLE
Can you please update the guzzlehttp/guzzle

### ISSUE THREAD

**Issue by omarname** [Dymantic/laravel-instagram-feed#13]
I get an error in installation saying dymantic/laravel-instagram-feed v2.3.1 requires guzzlehttp/guzzle ^6.5

I have a project using laravel 8 and "guzzlehttp/guzzle": "^7.0.1"

Can you please update the dependency

**Comment by michaeljoyner** [comment]
Sure, no problem. I'll do it as soon as I get back home, in a couple of hours time.

**Comment by michaeljoyner** [comment]
Should be done now (v2.3.2)

**Comment by omarname** [comment]
thank youuuuuu a lot man you are a great job.
