### ISSUE TITLE
A new migration file is created everytime I run "php artisan vendor:publish"

### ISSUE THREAD

**Issue by olakulehinayomide** [Dymantic/laravel-instagram-feed#2]
A new copy of the migration file is created every time I run **php artisan vendor:publish** which throws an error when I run migration. This is because a migration file has been created before with the class.

**Comment by michaeljoyner** [comment]
Hi @olakulehinayomide thanks for the help. I see the issue and I'll fix it tomorrow morning, unless you send a PR before that.

**Comment by olakulehinayomide** [comment]
Thanks for your response @michaeljoyner. I created a PR already.
