### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by geo903** [Dymantic/laravel-instagram-feed#23]
Hello! When updating i get this error:

`{
   "error": {
      "message": "Syntax error \"Expected \"(\" instead of \",\".\" at character 75: caption,id,media_type,media_url,thumbnail_url,permalink,children.media_type,children.media_url,timestamp",
      "type": "IGApiException",
      "code": 2500,
      "fbtrace_id": "AGDh0xebtg5Q1zRB8TaOlBd"
   }
}`

**Comment by michaeljoyner** [comment]
Hi @geo903 To fix this you need to update to the latest version (2.4.3). Facebook/Instagram changed how the query string should be written, which broke the version you are using. Upgrading should fix it. Sorry about that.
