### ISSUE TITLE
Config APP_URL

### ISSUE THREAD

**Issue by joselvil** [Dymantic/laravel-instagram-feed#25]
Hi Thank you for a remarkable package.
I'm currently using this.

Is there a way where instead of using .env APP_URL variable, use
other .env variables? without editing the package?

![image](https://user-images.githubusercontent.com/29266282/117091410-c90d0600-ad8d-11eb-8247-91ac01915b06.png)

I'm asking this currently my project is running subdomains, I'm having problem with regards to the callback parameter because of my subdomains

**Comment by michaeljoyner** [comment]
Hi @joselvil Thanks for the kind words. I have added a `base_url` option to the config file, which you can use to override the APP_URL. If you update to v2.4.4 you should be able to add it to your config file and it should work. Let me know if there are any issues.

**Comment by joselvil** [comment]
Thank you for the response.
I tested it and it works flawlessly thank you again.

👍👍👍
