### ISSUE TITLE
Empty array on $profile->feed()

### ISSUE THREAD

**Issue by amirehman** [Dymantic/laravel-instagram-feed#26]
Hello, 

I am getting an empty array on $profile->feed(), I am using Laravel 8. 

I followed the provided tutorial step by step, everything is perfect without error. the application got allowed with the link and successfully redirected to the provided callback URL, and the token has been generated. But when I try to fetch data with the feed method, I get an empty array without any error.

**Comment by michaeljoyner** [comment]
Hi @amirehman, sorry about that. The `feed` method is meant to fail silently (if an error occurs it will just return an empty array), so I suspect that an exception is being thrown somewhere. Please can you try use the `$profile->refreshFeed()` method and see if an Exception is thrown. This might give us a clue about what is happening.

**Comment by amirehman** [comment]
Thanks, @michaeljoyner for the quick reply. 
Yes! you are right. after change feed() to refreshFeed(), Now I am getting this server error. 

`Server error: `GET https://graph.instagram.com/17841405080329449/media?fields=caption,id,media_type,media_url,thumbnail_url,permalink,children.media_type,children.media_url&limit=4&access_token=IGQVJVOWJqdHZAqM3lPMFFQR053cGlEZAkRVeDJabTdka2t4UHpZASzdDaWthTGJueXdfaG9pY1diTGdubUZAvckMxUUdEUllnRGR2VFc5YVEwbF9BVEMzLURmSVlORWNWNU13U0UtWVVn` resulted in a `500 Internal Server Error` response: {"error":{"message":"Syntax error \"Expected \"(\" instead of \",\".\" at character 75: caption,id,media_type,media_url, (truncated...)` 

![Uploading Screen Shot 2021-05-06 at 12.26.03 PM.png…]()

**Comment by amirehman** [comment]
Thanks, @michaeljoyner for the quick reply. 
Yes! you are right. after change feed() to refreshFeed(), Now I am getting this server error. 

`Server error: `GET https://graph.instagram.com/17......49/media?fields=caption,id,media_type,media_url,thumbnail_url,permalink,children.media_type,children.media_url&limit=4&access_token=IGn` resulted in a `500 Internal Server Error` response: {"error":{"message":"Syntax error \"Expected \"(\" instead of \",\".\" at character 75: caption,id,media_type,media_url, (truncated...)`

**Comment by michaeljoyner** [comment]
Great, thanks. I know what the issue is now. If you upgrade to 2.4.3 or later it should fix that.

**Comment by amirehman** [comment]
WoW! Awesome! the upgrade worked. Thank you so much for this amazing package.
