### ISSUE TITLE
Image thumbnail

### ISSUE THREAD

**Issue by Digitalmx** [Dymantic/laravel-instagram-feed#27]
Hi michaeljoyner,
I hope that you are doing well, I have been used "laravel-instagram-feed" package to get and show the instagram feeds and it is working fine. I am very impresses with this package and I will recommend to all of you to use it to show the instagram feeds. I am facing a issue, how to fetch the thumbnail size of the image, because when I fetch the feeds and show the feed image in small div size, then the image will lose the quality. Please help me to fix it. 
Thanks

**Comment by michaeljoyner** [comment]
Hi @Digitalmx, thank you for the kind words, I'm glad you find the package useful. I'm not sure if Instagram still providers the thumbnail url, but I will look into it, as it would be very useful. It's a little late in the day here, so I'll only get to it tomorrow morning.

**Comment by michaeljoyner** [comment]
Hi there. Sorry, I didn't get any time for this on the weekend. Unfortunately it seems that there is no way currently to get thumbnail image urls from the API. If this is something that changes in the future I will definitely include it, but for now I can't really do anything.
