### ISSUE TITLE
Force Instagram Re-authentication

### ISSUE THREAD

**Issue by joselvil** [Dymantic/laravel-instagram-feed#28]
Hi Michael good day its me again.

Would like to know if its possible for instagram re-authentication when
fetching basic display data?

currently after first successful instagram feed acquisition the account remains logged in instagram
and when I try to fetch a different account feed I need to log out first from instagram with the previous account
before fetching new instagram account feed

**Comment by michaeljoyner** [comment]
Hi @joselvil I would need to know a bit more about how you are doing things. Once you have authenticated a profile you don't need to do any more authenticating when you fetch the feed. So you should be able to do the auth flow for one profile, then do the auth flow for a second profile (you of course will have to log in to the correct account on IG each time you authorize) and then you should be able to fetch from each profile whenever you need without doing any more auth/logging in.

**Comment by joselvil** [comment]
(you of course will have to log in to the correct account on IG each time you authorize) => is there a way mitigating this?

**Comment by michaeljoyner** [comment]
The authorisation only needs to be done once. Once it is done for each profile, that profile has its own access token that allows it to fetch the feed from instagram, you don't need to redo the authorisation again unless you let the the token expire (or something happens to the database, etc). The package has no control of what IG account you are logged into in your browser.

**Comment by joselvil** [comment]
Thank you Michael
