### ISSUE TITLE
How to get feed without adding users as app testers

### ISSUE THREAD

**Issue by joselvil** [Dymantic/laravel-instagram-feed#29]
Hi Michael its me again sorry to bug you.

Do we need to always add users as app testers in facebook developers ? to get the feeds.
I switched my facebook app to live mode but when I logged in instagram using a non tester account
it returned error code 400 invalid scope.

**Comment by joselvil** [comment]
Do I need to complete this first?

![image](https://user-images.githubusercontent.com/29266282/118573073-6451a280-b7b4-11eb-9053-3528f1ad1f20.png)

**Comment by michaeljoyner** [comment]
Hi @joselvil Yes, you need to get your IG app verified

**Comment by joselvil** [comment]
Thank you Michael
