### ISSUE TITLE
Overwritable credentials using state ID

### ISSUE THREAD

**Issue by adsy2010** [Dymantic/laravel-instagram-feed#30]
Initially I created a profile using the artisan command supplied.

So now I have `Profile::find(1);` available to me

I then created the link as below, obfuscated the real data of course but left the structure:

https://api.instagram.com/oauth/authorize/?client_id=1234567890&redirect_uri=https://site.com/instagram/auth/callback&scope=user_profile,user_media&response_type=code&state=1

`state=1` at the end is the user ID from what I can see. I can follow this link as a different user and authorise against that id.

Data stored in feed tokens is not the same username as the one on the profiles table but is linked to the profile ID in the profile table.

So now when I call `$profile->feed()` I get the feed for the profile I just authorised and not the username that's stored in the profile table.

Suggested solution would be to check the username returned is the same as the one that state id is expecting, otherwise create the profile line and give it a new ID OR throw an error and not accept the account.

**Comment by michaeljoyner** [comment]
Hi @adsy2010 Thank you very much for pointing that out. I guess it is a bit naive to use the user id directly like that. I may be wrong, but checking the username has the issue that the username is unknown when first authenticating a new profile.

A possible solution is to use the session to keep track of the profile, but then we are forced to do the whole auth flow in the same session, which I guess is fairly normal. Another solution would be to use the DB, but then it would require people to add a migration when the upgrade.

**Comment by adsy2010** [comment]
I suspect it will be usage based needs.

The usage scenario for me is a single Instagram account feed to be displayed on a site. Apart from an initial setup, I wouldn't expect any further Instagram connections to take place so would find using the profiles database table username to be the same as on the tokens table.

I would be supplying a one time authorisation link to be used to authorise initially so would probably not have a website session with the same ID on the callback. This could be stored alongside the username in the profiles table, if it exists, use that instead of the id on the returned `state` value. This can then be overwritten so that the original link becomes a dud but I don't think this would affect the refresh feature.

As you suggested, this does use the DB. I haven't used v1 so I don't know the difference in requirements and therefore cannot comment on that.

**Comment by michaeljoyner** [comment]
I agree with you, using the session is not ideal and I do think that storing some kind of identifier in the DB is the best way forward, but that will require a major release, which I will do soon. Thanks for helping me think through this.

**Comment by michaeljoyner** [comment]
This has (finally) been taken care of for v3
