### ISSUE TITLE
Redirect to instagram-auth-failure

### ISSUE THREAD

**Issue by joselvil** [Dymantic/laravel-instagram-feed#31]
![image](https://user-images.githubusercontent.com/29266282/119597971-a44c0180-be14-11eb-9ccd-c5141fb1dabb.png)

Hi Michael, its me again. We were granted permission from facebook to use instagram_graph_user_profile & instagram_graph_user_media but when I try to use a non tester instagram account im always redirected to instagram-auth-failure route. If I connect using a tester account everything works fine. Is there a way to view the error or exception?

Im sorry for my bad english.
Thank you always for your help and for this great package.

**Comment by michaeljoyner** [comment]
Hi @joselvil sorry that I didn't get to this today, I didn't have much time. I'll try release a version tomorrow morning that will log the exception for you

**Comment by michaeljoyner** [comment]
Hi @joselvil If you upgrade to v2.4.5 the errors should be logged. Please let me know if this helps or not. Thanks.
