### ISSUE TITLE
How do I get a user's avatar?

### ISSUE THREAD

**Issue by RomanDolzhenko** [Dymantic/laravel-instagram-feed#36]
Trying to use $profile->viewData() but says there is no avatar.
![image](https://user-images.githubusercontent.com/24434079/124393089-72766680-dd01-11eb-99d8-cfd6df3b2442.png)

**Comment by michaeljoyner** [comment]
Hi @RomanDolzhenko Unfortunately the avatar and fullname are no longer provided by the Instagram Basic Display API, and those keys will be removed from the array in the next version.
