### ISSUE TITLE
Instagram refresh command - specify feed items

### ISSUE THREAD

**Issue by adsy2010** [Dymantic/laravel-instagram-feed#37]
Before I start, this is a request which I could put a PR in or leave up to you to determine whether to add it or not.

When refreshing a profiles feed using the refresh feed method, you can optionally choose a number of items `$profile->refreshFeed(10)` for example. The refresh command currently cycles through all profiles and refreshes by the default number which is 20. I propose adding an optional input to the refresh command `{feedItems?}` to use as the refresh feed item quantity.

Let me know what you think.

**Comment by michaeljoyner** [comment]
Hi @adsy2010, that is great suggestion, thanks. I had totally overlooked that. You are more than welcome to open a PR (it would be greatly appreciated), if not I will try to get to it sometime this weekend.

**Comment by adsy2010** [comment]
I'll try and get a pull request sorted a bit later on today for you

**Comment by adsy2010** [comment]
I have added a pull request for you #38

**Comment by michaeljoyner** [comment]
Much appreciated, thanks!
