### ISSUE TITLE
Limit and fields

### ISSUE THREAD

**Issue by m-lotze** [Dymantic/laravel-instagram-feed#4]
Is there a reason why the limit of feed items is hardcoded to 20? Could you make this configurable, so that we can get more items? Or even better, add some kind of pagination, like 

```
Profile {
...
    public function feed($limit = 20; $start = 0) {
         ...
    }
...
}
```

And please add more fields than just the type and media_url. e.g. the caption and the id would be good, so we can link directly to the post.

**Comment by michaeljoyner** [comment]
Hi @m-lotze, thanks for the feedback. There is no real reason anymore, I guess it's all I needed at the time. Your requests are all good ideas, and I agree should be done. You may either submit a PR or I will get to it in the next day or two.

**Comment by michaeljoyner** [comment]
Okay, I have added the id and caption fields, you will need to upgrade to v2.1 and up. I will get to the pagination/limit issue later.

**Comment by michaeljoyner** [comment]
I have opened a pull-request for the limit issue, see #5. Any discussion on that topic can go into that pull request.

For pagination, it involves more work that just passing in a query parameter. For example, if I wanted to start from item 10, I would first have to send a request with a limit of 9, and see if the response provides a "next" endpoint for me to use. If not, there is no item 10, if there is, then I would fetch the desired results in a second request, using that "next" endpoint. This is functionality that I don't really need or see myself needing so if you really want it, I would appreciate it if you could send a PR.  

In the mean time, I'm going to close this issue.
