### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by ateequrrahman97** [Dymantic/laravel-instagram-feed#42]
![Screenshot from 2021-10-05 13-18-06](https://user-images.githubusercontent.com/74288984/135986510-fff5ddb8-aa20-4914-beb2-d81551517521.png)
@michaeljoyner

**Comment by michaeljoyner** [comment]
Hi @ateequrrahman97 can I ask which version you are using?

**Comment by ateequrrahman97** [comment]
> Hi @ateequrrahman97 can I ask which version you are using?

"laravel/framework": "^7.24",
"dymantic/laravel-instagram-feed": "^2.6",

**Comment by michaeljoyner** [comment]
Thanks. Sorry, I make a mistake in the tutorial, if that was what you were following. You can try do:

`$profile = \Dymantic\InstagramFeed\Profile::where('username', ''`

**Comment by ateequrrahman97** [comment]
> Thanks. Sorry, I make a mistake in the tutorial, if that was what you were following. You can try do:
> 
> `$profile = \Dymantic\InstagramFeed\Profile::where('username', 'event_scape')->get()->first()`

Thanks, now it's working.

**Comment by ateequrrahman97** [comment]
My access_code was not saved in the database.
I am using ngrok for HTTPS
Auth URL is working fine and redirect to not found but access_code was not saved.
If you please guide me?
@michaeljoyner

**Comment by michaeljoyner** [comment]
What url does it redirect to?

**Comment by ateequrrahman97** [comment]
> What url does it redirect to?

https://2fb4-202-163-123-230.ngrok.io/instagram/auth/callback?code=AQDJNxTKR28HnronMXkyntwT3mZOTRjWtV0CbSpxlw5kHbCFqS6sInc2X4BDcyQ3s7bAtRL5jgYKi0yF-MZWBBxWLy0dtMlcvVZEqWgt2bAYei-IChbe0Snnw4cmyVsW8kQFNlnSkutNgPxrVnnwnSCxvxbowZBTKSbL4PojMqzm3wAsg2yqHXaa-CDR2qkhoX35RiBAs39alvTA11REdHw22S1kjBTjXlf2tbtiYhdMbA&state=1#_

**Comment by michaeljoyner** [comment]
And when you get redirected to the not found page, what is in the url?

**Comment by ateequrrahman97** [comment]
> And when you get redirected to the not found page, what is in the url?
This URL I use to authenticate
https://api.instagram.com/oauth/authorize/?client_id=2664228980539775&redirect_uri=https://2fb4-202-163-123-230.ngrok.io/instagram/auth/callback&scope=user_profile,user_media&response_type=code&state=1

And this is the redirected not found URL after authentication
https://2fb4-202-163-123-230.ngrok.io/instagram/auth/callback?code=AQDJNxTKR28HnronMXkyntwT3mZOTRjWtV0CbSpxlw5kHbCFqS6sInc2X4BDcyQ3s7bAtRL5jgYKi0yF-MZWBBxWLy0dtMlcvVZEqWgt2bAYei-IChbe0Snnw4cmyVsW8kQFNlnSkutNgPxrVnnwnSCxvxbowZBTKSbL4PojMqzm3wAsg2yqHXaa-CDR2qkhoX35RiBAs39alvTA11REdHw22S1kjBTjXlf2tbtiYhdMbA&state=1#_

**Comment by michaeljoyner** [comment]
Can you show me your config file? Also, I'll be gone for a while, but I'll be back later

**Comment by ateequrrahman97** [comment]
> Can you show me your config file? Also, I'll be gone for a while, but I'll be back later
Okay. Please look into it when you are back.

`<?php

return [
    /*
     * The client_id from registering your app on Instagram
     */
    'client_id'           => env('INSTAGRAM_APP_ID'),

    /*
     * The client secret from registering your app on Instagram,
     * This is not the same as an access token.
     */
    'client_secret'       => env('INSTAGRAM_APP_SECRET'),

    /*
     * The base url used to generate to auth callback route for instagram.
     * This defaults to your APP_URL, so normally you may leave it as null
     */
    'base_url' => null,

    /*
     * The route that will respond to the Instagram callback during the OAuth process.
     * Only enter the path without the leading slash. You need to ensure that you have registered
     * a redirect_uri for your instagram app that is equal to combining the
     *  app url (from config) and this route
     */
    'auth_callback_route' => 'https://2fb4-202-163-123-230.ngrok.io/instagram/auth/callback',

    /*
     * On success of the OAuth process you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'success_redirect_to' => 'https://2fb4-202-163-123-230.ngrok.io/instagram-auth-success',

    /*
     * If the OAuth process fails for some reason you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'failure_redirect_to' => 'https://2fb4-202-163-123-230.ngrok.io/instagram-auth-failure',

    /*
     * You may filter out video media types by setting this to true. Carousel media
     * will become the first image in the carousel, and if there are no images, then
     * the entire carousel will be ignored.
     */
    'ignore_video' => false,

    /*
     * You may set an email address below if you wish to be notified of errors when
     * attempting to refresh the Instagram feed.
     */
    'notify_on_error' => null,
];
`
Firstly I have used this way

`'auth_callback_route' => 'instagram/auth/callback',

    /*
     * On success of the OAuth process you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'success_redirect_to' => 'instagram-auth-success',

    /*
     * If the OAuth process fails for some reason you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'failure_redirect_to' => 'instagram-auth-failure',`

but then access_code was not saved then I have done in this way

`'auth_callback_route' => 'https://2fb4-202-163-123-230.ngrok.io/instagram/auth/callback',

    /*
     * On success of the OAuth process you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'success_redirect_to' => 'https://2fb4-202-163-123-230.ngrok.io/instagram-auth-success',

    /*
     * If the OAuth process fails for some reason you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'failure_redirect_to' => 'https://2fb4-202-163-123-230.ngrok.io/instagram-auth-failure',`
    
    Byt getting the same result.

**Comment by michaeljoyner** [comment]
The routes in your config file shouldn't have the domain part in them. Can you change back to that and send me a screenshot of what happens after you accept the sith request on Instagram?

**Comment by michaeljoyner** [comment]
Sorry, forgot to mention that you can also add the ngrok domain as the base_url in your config file

**Comment by ateequrrahman97** [comment]
> Sorry, forgot to mention that you can also add the ngrok domain as the base_url in your config file

Thank you @michaeljoyner for giving me your attention. It is working by putting a base URL.
Thanks.

**Comment by michaeljoyner** [comment]
It's a pleasure, I'm glad you got it working.
