### ISSUE TITLE
Laravel 8 - Class "Dymantic\InstagramFeed\InstagramFeed" not found

### ISSUE THREAD

**Issue by kinger251285** [Dymantic/laravel-instagram-feed#47]
Hi 

Just installed the package, published the vendor files, updated the config and migrated the migrations to the database. All worked fine. Can see the package in the vendor folder.  However i am getting the error - Class "Dymantic\InstagramFeed\InstagramFeed" not found

`$feed = \Dymantic\InstagramFeed\InstagramFeed::for('my_profile');`

**Comment by michaeljoyner** [comment]
Hi @kinger251285 , sorry to hear you are having a problem. I will need a bit more info to be able to help you., but I suspect you have installed version 2, but looking at the instructions for version 3. If for some reason you cannot use v3, you can see the README for v2 [here](https://github.com/Dymantic/laravel-instagram-feed/tree/v2.6.0)

**Comment by kinger251285** [comment]
Hi @michaeljoyner thanks for coming back to me. I followed the instructions as per the main github page here - https://github.com/Dymantic/laravel-instagram-feed

Ive not chosen version 2.

What other info would you need to diagnose?

**Comment by kinger251285** [comment]
Looks like you were right, version 2.6 had been installed due to my system php dropping back to version 7.4 for some reason. May  be common knowledge but may be worth noting somewhere in the docs that the version installed is based on system variables.

Thanks for coming back so quickly and thanks for your help.

**Comment by michaeljoyner** [comment]
I'm glad you got it sorted out. I'll add a note to the readme as you suggested. Thanks.
