### ISSUE TITLE
Error validating access token: Session has expired on Saturday, 05-Feb-22 07:56:09 PST

### ISSUE THREAD

**Issue by ateequrrahman97** [Dymantic/laravel-instagram-feed#49]
Hello, @michaeljoyner hope you are doing well!
It's not an issue but I want some dynamic implementation for that,
Is there any way to refresh the token before the expiration of the session using a cron job?
But I know that to authenticate the package provides the URL.
Please look into it.
Thanks

**Comment by michaeljoyner** [comment]
Hi @ateequrrahman97 I am doing very well thanks.

There is an artisan command to refresh the tokens, you'd just need to make sure it is run every few days. See the docs [here](https://github.com/Dymantic/laravel-instagram-feed#refreshing-access-tokens)

**Comment by ateequrrahman97** [comment]
> Hi @ateequrrahman97 I am doing very well thanks.
> 
> There is an artisan command to refresh the tokens, you'd just need to make sure it is run every few days. See the docs [here](https://github.com/Dymantic/laravel-instagram-feed#refreshing-access-tokens)

Thanks, @michaeljoyner 
I really miss that.
