### ISSUE TITLE
Laravel 9 Support?

### ISSUE THREAD

**Issue by myurtsev** [Dymantic/laravel-instagram-feed#50]
Tried to install on Laravel 9.0.1, PHP 8.1.2

`Problem 1
    - Root composer.json requires dymantic/laravel-instagram-feed ^3.0 -> satisfiable by dymantic/laravel-instagram-feed[v3.0.0].
    - dymantic/laravel-instagram-feed v3.0.0 requires illuminate/config ^7.0 | ^8.0 -> found illuminate/config[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.`

**Comment by michaeljoyner** [comment]
Hi @myurtsev thanks for opening this. I have just added Laravel 9 support in v3.1.1. Please let me know if there are any issues with using it with Laravel 9. Thanks.

**Comment by myurtsev** [comment]
Thank you for the quick fix. Works like a charm!
