### ISSUE TITLE
we need a route that Instagram will redirect the user to once they have given permission.

### ISSUE THREAD

**Issue by talkwithdeveloper** [Dymantic/laravel-instagram-feed#55]
How to create a route in web.php file . we don't have mention any controller and function inside the route ?if not how we will get the "code" from querystring and move further .
Route::get('instagram/auth/callback', 'InstgramAuthController'); 
i am little confuse about to create route after user allow to access his/her account.

**Comment by michaeljoyner** [comment]
Hi @talkwithdeveloper, you don't need to create the route or controller, the package manages all that for you. You are able to set the routes in the config file if you are using routes that do not match the default. Please see the readme file for instructions.

**Comment by talkwithdeveloper** [comment]
HI @michaeljoyner , I have read readme file instruction , according to that i have set the config file fields value,  but when user allow the permission on instagram URL page and then its come back to redirect url, its show 404 [error](
![Screenshot_1](https://user-images.githubusercontent.com/26228951/165887812-0d0bea1c-fcf1-4e28-8476-339390820d0a.png)
![Screenshot_2](https://user-images.githubusercontent.com/26228951/165887807-2bdc1a47-9fc8-49e9-ba69-d9e1e2717c31.png))

**Comment by michaeljoyner** [comment]
Can you show me your config file?

**Comment by talkwithdeveloper** [comment]
<?php

return [
    /*
     * The client_id from registering your app on Instagram
     */
    'client_id'           => '397489588877863',

    /*
     * The client secret from registering your app on Instagram,
     * This is not the same as an access token.
     */
    'client_secret'       => 'cf516372572113e08f37e6396993ff2b',

    /*
     * The base url used to generate to auth callback route for instagram.
     * This defaults to your APP_URL, so normally you may leave it as null
     */
    'base_url' => null,

    /*
     * The route that will respond to the Instagram callback during the OAuth process.
     * Only enter the path without the leading slash. You need to ensure that you have registered
     * a redirect_uri for your instagram app that is equal to combining the
     *  app url (from config) and this route
     */
    'auth_callback_route' => 'instagram/auth/callback',

    /*
     * On success of the OAuth process you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'success_redirect_to' => 'instagram-auth-success',

    /*
     * If the OAuth process fails for some reason you will be redirected to this route.
     * You may use query strings to carry messages
     */
    'failure_redirect_to' => 'instagram-auth-failure',

    /*
     * You may filter out video media types by setting this to true. Carousel media
     * will become the first image in the carousel, and if there are no images, then
     * the entire carousel will be ignored.
     */
     'ignore_video' => false,

    /*
     * You may set an email address below if you wish to be notified of errors when
     * attempting to refresh the Instagram feed.
     */
    'notify_on_error' => null,
];
?>

**Comment by michaeljoyner** [comment]
What is set as your APP_URL? If you are using subdomains, your may need to use the 'base_url' option in the config file. See [issue 25](https://github.com/Dymantic/laravel-instagram-feed/issues/25)

**Comment by talkwithdeveloper** [comment]
yes i am using subdomian

**Comment by talkwithdeveloper** [comment]
![Uploading Screenshot_3.png…]()

**Comment by talkwithdeveloper** [comment]
so in base url what url should i used ?
subdomian and domian ?

**Comment by michaeljoyner** [comment]
Yes, everything that should come before /instagram/auth/callback. So http://subdomain.domain.com

**Comment by talkwithdeveloper** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/26228951/165901127-4525685e-366c-4104-9fc8-5abc0109e2f8.png)

**Comment by talkwithdeveloper** [comment]
I have added but still same error

**Comment by talkwithdeveloper** [comment]
Got it 
Thanks @michaeljoyner

**Comment by talkwithdeveloper** [comment]
Problem is i have made folder with name instagram inside the subdomian

**Comment by talkwithdeveloper** [comment]
I have sent all file to root of subdomian and remove the instagram folder

**Comment by talkwithdeveloper** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/26228951/165909678-095ec7f7-9d7a-429e-9134-e61d581a7f6c.png)

**Comment by michaeljoyner** [comment]
You can probably put the entire route (starting from https://) in the config file for the success_redirect

**Comment by talkwithdeveloper** [comment]
okay

**Comment by talkwithdeveloper** [comment]
Added But same error

**Comment by michaeljoyner** [comment]
Sorry, you don't need to use the whole route. You need to create the route and view for these on your own, the package just redirects to the route you define in your config. From your screenshot above, everything is fine. In your routes file you need to create the 'instagram-auth-success' route and handle it how you want.
